/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WiFiConfig = IDL.Record({
  'signalStrength' : IDL.Int,
  'ssid' : IDL.Text,
  'interferenceLevel' : IDL.Float64,
  'frequency' : IDL.Nat,
  'channel' : IDL.Nat,
});
export const OptimizationRecommendation = IDL.Record({
  'signalImprovement' : IDL.Opt(IDL.Int),
  'recommendedFrequency' : IDL.Opt(IDL.Nat),
  'recommendedChannel' : IDL.Opt(IDL.Nat),
});
export const SpeedTestResult = IDL.Record({
  'timestamp' : IDL.Int,
  'downloadSpeed' : IDL.Float64,
});

export const idlService = IDL.Service({
  'analyzeWiFi' : IDL.Func(
      [WiFiConfig],
      [OptimizationRecommendation],
      ['query'],
    ),
  'getSpeedTestTrend' : IDL.Func([], [IDL.Vec(SpeedTestResult)], ['query']),
  'recordSpeedTest' : IDL.Func([SpeedTestResult], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WiFiConfig = IDL.Record({
    'signalStrength' : IDL.Int,
    'ssid' : IDL.Text,
    'interferenceLevel' : IDL.Float64,
    'frequency' : IDL.Nat,
    'channel' : IDL.Nat,
  });
  const OptimizationRecommendation = IDL.Record({
    'signalImprovement' : IDL.Opt(IDL.Int),
    'recommendedFrequency' : IDL.Opt(IDL.Nat),
    'recommendedChannel' : IDL.Opt(IDL.Nat),
  });
  const SpeedTestResult = IDL.Record({
    'timestamp' : IDL.Int,
    'downloadSpeed' : IDL.Float64,
  });
  
  return IDL.Service({
    'analyzeWiFi' : IDL.Func(
        [WiFiConfig],
        [OptimizationRecommendation],
        ['query'],
      ),
    'getSpeedTestTrend' : IDL.Func([], [IDL.Vec(SpeedTestResult)], ['query']),
    'recordSpeedTest' : IDL.Func([SpeedTestResult], [], []),
  });
};

export const init = ({ IDL }) => { return []; };